global:
  resolve_timeout: 5m
receivers:
- name: default-telegram
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 0000000000:AAAAbCCDDELy2xzYko-cIZ-oT2Em1bCyTJY
    chat_id: -1001859723546
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""
route:
  continue: false
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: default-telegram
  repeat_interval: 4h
  routes:
  - receiver: default-telegram
templates:
- /etc/alertmanager/config/*.tmpl
