route:
  - match:
      severity: send-telegram
    receiver: stardata-telegram

receivers:
 
- name: 'stardata-telegram'
  telegram_configs:
  - bot_token: 6612780049:AAFN1EPIxZJYZwURiMC3Cx1XYEFlDeeNdOs
    api_url: https://api.telegram.org
    chat_id: -1001859723546
    parse_mode: 
