---
- hosts: all
  become: true
  tasks:
#    - name: Обновить кэш пакетов
#      apt:
#        update_cache: yes
#      when: ansible_os_family == "Debian"

#    - name: Установить Nginx, Docker и другие зависимости
#      apt:
#        name: ['nginx', 'docker.io']
#        state: present
#      when: ansible_os_family == "Debian"
#
#    - name: Запустить Nginx и добавить в автозапуск
#      service:
#        name: nginx
#        state: started
#        enabled: yes
#      when: ansible_os_family == "Debian"


    - name: Клонирование репозитория
      git: repo={{ repo_url }}/{{ repo }}.git
        dest={{ repo_dir }}
        version={{ repo_branch }}
        accept_hostkey=yes
      become_user: ubuntu

    - name: Сборка контейнера и его запуск 
      shell: |
        docker stop {{ container_name }}
        docker rm {{ container_name }}
        docker build -t {{ full_name }} {{ repo_dir}}/.
        docker run -d --name {{ container_name }} -p {{ ext_port }}:{{ int_port }} {{ full_name }}
        docker push {{ full_name }}
      become: yes

    - name: Отправка контейнера в хранилище артефактов(ghcr.io)
      shell: |
        docker push {{ full_name }}
      become: yes
